apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qn307nmsg-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qn307nmsg-nodejs 
  name: qn307nmsg-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: qn307nmsg-nodejs 
